

version: '2'

volumes:
    prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=720h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    build: './grafana'
    restart: unless-stopped
    links:
      - prometheus
    ports:
      - '3000:3000'
